# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/longreadtools',
                'doc_host': 'https://cobioda.github.io',
                'git_url': 'https://github.com/cobioda/longreadtools',
                'lib_path': 'longreadtools'},
  'syms': {'longreadtools.core': {'longreadtools.core.foo': ('core.html#foo', 'longreadtools/core.py')}}}
