# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/longreadtools',
                'doc_host': 'https://cobioda.github.io',
                'git_url': 'https://github.com/cobioda/longreadtools',
                'lib_path': 'longreadtools'},
  'syms': { 'longreadtools.core': {'longreadtools.core.foo': ('tests.html#foo', 'longreadtools/core.py')},
            'longreadtools.isomatrix_tools': { 'longreadtools.isomatrix_tools.isomatrix_to_anndata': ( 'isomatrix_tools.html#isomatrix_to_anndata',
                                                                                                       'longreadtools/isomatrix_tools.py')}}}
