# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/transfer_annotations.ipynb.

# %% auto 0
__all__ = ['subset_common_cells']

# %% ../nbs/transfer_annotations.ipynb 4
import scanpy as sc
def subset_common_cells(dataset1, dataset2):
    return dataset1[dataset1.obs.index.isin(dataset2.obs_names),:]
